# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

#env:
#  shell: bash
#  variables:
#    GIT_TAG: expr $(shell git rev-parse --short HEAD 2> /dev/null)
#    API_BUILD_TAG: expr $(if $(BUILD_TAG),$(BUILD_TAG),aws-tests-sample-node-js/aws-tests-sample-node-js:$(GIT_TAG))
#    API_ECR_TAG: expr $(if $(API_ECR_TAG),$(API_ECR_TAG), $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo setting env variables
      - export GIT_TAG=$(shell git rev-parse --short HEAD 2> /dev/null)
      - echo $GIT_TAG
      - export API_BUILD_TAG=$(if $(BUILD_TAG),$(BUILD_TAG),aws-tests-sample-node-js/aws-tests-sample-node-js:$(GIT_TAG))
      - export API_ECR_TAG=$(if $(API_ECR_TAG),$(API_ECR_TAG), $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Logging into ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo ls command
      - ls -la
      - echo Running Tests
      - npm test
      - npm --version
      - docker --version
      - echo $AWS_ACCOUNT_ID
      - echo $IMAGE_TAG
      - echo $IMAGE_REPO_NAME
      - echo $AWS_DEFAULT_REGION
      - echo API_ECR_TAG and API_BUILD_TAG
      - echo $API_BUILD_TAG
      - echo $API_ECR_TAG
      - docker images
#      - docker build -t aws-tests-sample-node-js/aws-tests-sample-node-js:latest .
      - docker build -t $(API_BUILD_TAG) .
      - echo Checking if container is present
      - docker images
      - docker tag aws-tests-sample-node-js/aws-tests-sample-node-js:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $(API_BUILD_TAG) $(API_ECR_TAG)
#      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Tests Complete
      - echo Build Complete on `date`
      - echo Pushing Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
